### ISSUE TITLE
[Feature-Request]: Phase spectra based on array

### ISSUE THREAD

**Issue by thorstenmaly** [DNPLab/DNPLab#172]
change phasing function to allow an array of p0 and p1 values (and pivot point) for phasing.

**Comment by thcasey3** [comment]
@thorstenmaly this is already an option, assuming it is functioning correctly. You must set ```order="first"``` and give ```phase=``` an array equal in length to the size of the given ```dim=```.  If an array is given, there should be no need to set a pivot, right? The data should be baseline corrected and the phase array made to cross the baseline wherever you want to pivot. Otherwise, ```pivot=``` is an integer specifying the point index of the pivot, default is 0. Set ```delta=``` to define the slope of the first order array and it is then calculated as a linear line using the int/float given for ```phase=```.

**Comment by thorstenmaly** [comment]
Thanks Tom, I need to take a look at this. Yen-Chun told me about this issue. Pivot point is required whenever you want to to do a first order correction. I would say the pivot point should be by default at the center of the spectrum, but I can check what TopSpin or VnmrJ is doing.

**Comment by tkeller12** [comment]
@thorstenmaly Will split the phase function into first order and zeroth order phase functions and close this issue.

**Comment by thorstenmaly** [comment]
This has been updated and is working.
We can revisit separating the phase function into individual functions in the future. However, they can always be accessed individually by setting one argument to 0.

**Comment by thorstenmaly** [comment]
Fixed
