### ISSUE TITLE
not clear why we need a data object and workspace, and when one is preferred over the other

### ISSUE THREAD

**Issue by thcasey3** [DNPLab/DNPLab#3]
It is not clear why we need a data object and workspace, and when one is preferred over the other. It seems all of the functions could be simplified and users would need a few less lines of code to accomplish the same if we just choose one

**Comment by thorstenmaly** [comment]
This needs a better description of the workflow in the documentation.

**Comment by thcasey3** [comment]
improved documentation in upcoming pull request will address this issue

**Comment by thcasey3** [comment]
@tkeller12 @thorstenmaly Functions like saveh5 can't handle a dnpdata object, only a dnpdata_collection, i.e. workspace. This highlights the question, why do we need both? Workspaces are more convenient, are intuitive, and contents of the workspace can be interacted with in an object oriented fashion. So why the need to import an object and convert to a workspace manually? I think all of the import functions should just make a dnpdata_collection (workspace) directly. In addition to removing the user's need to manually create a workspace, all of the code for recognition and normalizing of the data at the beginning of most of the functions can be removed, which will be a reduction in complication and probably also execution times. This would also likely close at least three other open issues. @ylin00 @jmfranck

**Comment by ylin00** [comment]
> @tkeller12 @thorstenmaly Functions like saveh5 can't handle a dnpdata object, only a dnpdata_collection, i.e. workspace. This highlights the question, why do we need both? Workspaces are more convenient, are intuitive, and contents of the workspace can be interacted with in an object oriented fashion. So why the need to import an object and convert to a workspace manually? I think all of the import functions should just make a dnpdata_collection (workspace) directly. In addition to removing the user's need to manually create a workspace, all of the code for recognition and normalizing of the data at the beginning of most of the functions can be removed, which will be a reduction in complication and probably also execution times. This would also likely close at least three other open issues. @ylin00 @jmfranck

Yes. It is somewhat cumbersome to maintain both workspace and dnpdata. Instead of dropping dnpdata, I think it is more practical to change/drop workspace. I listed two questions below along with my suggestions. 

1. What does "workspace" mean without too much learning? Currently the workspace is implemented as a dictionary of dnpdata. However, such data structure is not obvious by just reading from its name. 
Solution: Renaming it into "DNPdataDict" maybe better. And it must behave as if it was a dictionary (i.e., having the update(), set(), get() etc)  

2. Why we need a dictionary of dnpdata? I believe @tkeller12 can answer this better. But on the following two reasons, I respectfully disagree. 
* For saving to h5 file: we might as well create the dictionary right before saving, instead of carrying a dictionary around, which is so abstract.
* For keeping track of the raw data: This appears unnecessary. Raw data is a DNPdata instance, which is by default **immutable** (unless one do some inplace modification). Therefore one can just keep a variable raw_data untouched, similar experience for matlab users. No need to carry the raw data around.

The dnpdata mimics numpy array with extra supports on coordinates, which you can do math on (data + data, data * 2, etc). I believe it should be retained rather than dropped from the documentation.
