### ISSUE TITLE
signal_to_noise function does not return expected value

### ISSUE THREAD

**Issue by tkeller12** [DNPLab/DNPLab#420]
The signal to noise function does not give the expected SNR value for data generated with a given SNR:
```
import dnplab as dnp

from matplotlib.pylab import *

pts = 100

x = np.r_[0.:99.:1j * pts]
y = dnp.lineshape.gaussian(x,50,5,integral = 1.0)

y /= np.max(y)
np.random.seed(100)
y += np.random.randn(pts) * 0.1


signal = np.max(y)
print('signal:', signal)
noise = np.std(y[70:100])
print('noise:', noise)

print('SNR:', signal / noise)


print(dnp.__file__)


data = dnp.DNPData(y, ['x'], [x])

snr = dnp.signal_to_noise(data, [(0,100)], dim = 'x', noise_region = [(70,100)])

print(snr)
print('dnplab:',snr.values)


figure()
plot(x,y)
show()
```

**Comment by Bkaribo** [comment]
```
pts = 100

x = np.r_[0.:99.:1j * pts]
y = dnp.lineshape.gaussian(x,50,5,integral = 1.0)

y /= np.max(y)
np.random.seed(100)
y += np.random.randn(pts) * 0.1



y = np.abs(y)
signal = np.max(y)
print('signal:', signal)
noise = np.std(y[70:99])
print('noise:', noise)

print('SNR:', signal / noise)


print(dnp.__file__)


data = dnp.DNPData(y, ['x'], [x])

snr = dnp.signal_to_noise(data, [(0,100)], dim = 'x', noise_region = [(70,99)])

print(snr)
print('dnplab:',snr.values)


figure()
plot(x,y)
show()
```

using this code (notice the changed noise_region) the two values do coincide
the reason is that the noise region is not selected by using an index but the dimension coords (which coincide here).
In the __getitem__method of ABCData the selection with coords/dims always excludes the last coord, this leads to a behavior that the last point will never be returned -> the SNR is here calculated with data(0:100) but in ABCData[0.0:100.0] will always exclude the last value because it will return ABCData[0:99] 
a possible fix will be added but it should be reviewed as it changed ABCData
